name: Typecheck
on:
  push:
    branches:
      - master
      - ci2
  pull_request:
env:
  LUA_LS_VERSION: 3.14.0
jobs:
  luals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make Directories
        run: |
          mkdir ci
          mkdir ci/luals
          mkdir ci/LuaCATS
      - name: Setup LuaLS
        run: curl -sL "https://github.com/LuaLS/lua-language-server/releases/download/${{ env.LUA_LS_VERSION }}/lua-language-server-${{ env.LUA_LS_VERSION }}-linux-x64.tar.gz" | tar xzf - -C "${PWD}/ci/luals"
      - name: Install luassert symbols
        uses: actions/checkout@v4
        with:
          repository: LuaCATS/luassert
          path: ci/LuaCATS/luassert
      - name: Install busted symbols
        uses: actions/checkout@v4
        with:
          repository: LuaCATS/busted
          path: ci/LuaCATS/busted
      - name: Run LuaLS
        run: |
          export PATH="${PWD}/ci/luals/bin:${PATH}"
          lua-language-server --configpath .luarc-ci.json --check . --checklevel=Hint
